db:
  image: mongo:3.0
  command: mongod --smallfiles --oplogSize 128
  volumes:
       - //./data/db:/data/db

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - PORT=3000
    - ROOT_URL=http://docker:3000
    - MONGO_URL=mongodb://db:27017/rocketchat
  links:
    - db:db
  ports:
    - 3000:3000